#if !defined( TEST_MAIN_H )
#define TEST_MAIN_H

// test_game.c
void Game_Init_Always_InitializesClock( void );
void Game_Init_Always_InitializesScreen( void );
void Game_Init_Always_InitializesInput( void );
void Game_Init_Always_InitializesAnimationChain( void );
void Game_Init_Always_InitializesTileMap( void );
void Game_Init_Always_InitializesViewports( void );
void Game_Tic_Always_RendersGame( void );
void Game_Tic_AnimationChainIsRunning_TicsAnimationChain( void );
void Game_Tic_AnimationChainIsNotRunning_DoesNotTicAnimationChain( void );
void Game_Tic_AnimationChainBlocksInput_DoesNotHandleInput( void );
void Game_Tic_AnimationChainIsNotBlockingInput_HandlesInput( void );
void Game_Tic_AnimationChainPausesAction_DoesNotPerformActions( void );
void Game_TicByState_GameStateIsOverworldActive_UpdatesDayFilterIntensity( void );
void Game_TicByState_GameStateIsOverworldAndNotActive_DoesNotUpdateDayFilterIntensity( void );
void Game_TicByState_GameStateIsOverworld_TicsTileMap( void );
void Game_TicByState_GameStateIsOverworld_TicsPhysics( void );
void Game_TicByState_GameStateIsOverworld_ClampsViewportToEntity( void );
void Game_HandlePlayerMoved_Always_UpdatesFrontPlayerMoveHistory( void );
void Game_HandlePlayerMoved_FrontPlayerMoveHistoryIndexOverflow_ChainsNextPlayer( void );
void Game_HandlePlayerMoved_Always_AnchorsRearPlayers( void );
void Game_HandlePlayerMoved_TileMapAffectsDaylight_IncrementsDaylightFactor( void );
void Game_HandlePlayerMoved_SteppedOnDifferentTile_StepsOnTile( void );

// test_input.c
void Input_Init_Always_SetsAllStatesToFalse( void );
void Input_AnyButtonPressed_NoButtonsPressed_ReturnsFalse( void );
void Input_AnyButtonPressed_ButtonWasPressed_ReturnsTrue( void );
void Input_HandleOverworldGeneral_OnlyLeftIsDown_VelocityIsCorrect( void );
void Input_HandleOverworldGeneral_OnlyUpIsDown_VelocityIsCorrect( void );
void Input_HandleOverworldGeneral_OnlyRightIsDown_VelocityIsCorrect( void );
void Input_HandleOverworldGeneral_OnlyDownIsDown_VelocityIsCorrect( void );
void Input_HandleOverworldGeneral_LeftAndUpAreDown_VelocitiesAreCorrect( void );
void Input_HandleOverworldGeneral_UpAndRightAreDown_VelocitiesAreCorrect( void );
void Input_HandleOverworldGeneral_RightAndDownAreDown_VelocitiesAreCorrect( void );
void Input_HandleOverworldGeneral_DownAndLeftAreDown_VelocitiesAreCorrect( void );
void Input_HandleOverworldGeneral_LeftIsDown_PlayerFacesLeft( void );
void Input_HandleOverworldGeneral_UpIsDown_PlayerFacesUp( void );
void Input_HandleOverworldGeneral_RightIsDown_PlayerFacesRight( void );
void Input_HandleOverworldGeneral_DownIsDown_PlayerFacesDown( void );
void Input_HandleOverworldGeneral_LeftAndUpAreDownAndPlayerIsFacingUp_PlayerKeepsFacingUp( void );
void Input_HandleOverworldGeneral_LeftAndUpAreDownAndPlayerIsNotFacingUp_PlayerFacesLeft( void );
void Input_HandleOverworldGeneral_UpAndRightAreDownAndPlayerIsFacingUp_PlayerKeepsFacingUp( void );
void Input_HandleOverworldGeneral_UpAndRightAreDownAndPlayerIsNotFacingUp_PlayerFacesRight( void );
void Input_HandleOverworldGeneral_RightAndDownAreDownAndPlayerIsFacingDown_PlayerKeepsFacingDown( void );
void Input_HandleOverworldGeneral_RightAndDownAreDownAndPlayerIsNotFacingDown_PlayerFacesRight( void );
void Input_HandleOverworldGeneral_DownAndLeftAreDownAndPlayerIsFacingDown_PlayerKeepsFacingDown( void );
void Input_HandleOverworldGeneral_DownAndLeftAreDownAndPlayerIsNotFacingDown_PlayerFacesLeft( void );
void Input_HandleOverworldGeneral_LeftAndRightAreDown_PlayerDirectionDoesNotChange( void );
void Input_HandleOverworldGeneral_UpAndDownAreDown_PlayerDirectionDoesNotChange( void );
void Input_HandleOverworldGeneral_LeftAndUpAndRightAreDownAndPlayerIsFacingHorizontal_PlayerKeepsFacingHorizontal( void );
void Input_HandleOverworldGeneral_LeftAndUpAndRightAreDownAndPlayerIsFacingDown_PlayerFacesUp( void );
void Input_HandleOverworldGeneral_LeftAndUpAndRightAreDownAndPlayerIsFacingUp_PlayerKeepsFacingUp( void );
void Input_HandleOverworldGeneral_UpAndRightAndDownAreDownAndPlayerIsFacingVertical_PlayerKeepsFacingVertical( void );
void Input_HandleOverworldGeneral_UpAndRightAndDownAreDownAndPlayerIsFacingLeft_PlayerFacesRight( void );
void Input_HandleOverworldGeneral_UpAndRightAndDownAreDownAndPlayerIsFacingRight_PlayerKeepsFacingRight( void );
void Input_HandleOverworldGeneral_RightAndDownAndLeftAreDownAndPlayerIsFacingHorizontal_PlayerKeepsFacingHorizontal( void );
void Input_HandleOverworldGeneral_RightAndDownAndLeftAreDownAndPlayerIsFacingUp_PlayerFacesDown( void );
void Input_HandleOverworldGeneral_RightAndDownAndLeftAreDownAndPlayerIsFacingDown_PlayerKeepsFacingDown( void );
void Input_HandleOverworldGeneral_DownAndLeftAndRightAreDownAndPlayerIsFacingHorizontal_PlayerKeepsFacingHorizontal( void );
void Input_HandleOverworldGeneral_DownAndLeftAndRightAreDownAndPlayerIsFacingUp_PlayerFacesDown( void );
void Input_HandleOverworldGeneral_DownAndLeftAndRightAreDownAndPlayerIsFacingDown_PlayerKeepsFacingDown( void );

// test_npc.c
void Npc_Init_Always_InitializesBasicParameters( void );
void Npc_Init_NpcWanders_InitializesWanderParameters( void );
void Npc_Init_NpcDoesNotWander_DoesNotInitializeWanderParameters( void );
void Npc_Tic_DoesNotWander_DoesNothing( void );
void Npc_Tic_Wanders_IncrementsElapsedSeconds( void );
void Npc_Tic_WandersAndIsWanderingAndActionHasElapsed_StopsMoving( void );
void Npc_Tic_WandersAndIsNotWanderingAndActionHasElapsed_StartsMoving( void );
void Npc_Tic_FacingLeftAndNotMovingLeftAndMovingUp_SetsDirectionToUp( void );
void Npc_Tic_FacingLeftAndNotMovingLeftAndNotMovingUpAndMovingRight_SetsDirectionToRight( void );
void Npc_Tic_FacingLeftAndNotMovingLeftAndNotMovingUpAndNotMovingRight_SetsDirectionToDown( void );
void Npc_Tic_FacingUpAndNotMovingUpAndMovingRight_SetsDirectionToRight( void );
void Npc_Tic_FacingUpAndNotMovingUpAndNotMovingRightAndMovingDown_SetsDirectionToDown( void );
void Npc_Tic_FacingUpAndNotMovingUpAndNotMovingRightAndNotMovingDown_SetsDirectionToLeft( void );
void Npc_Tic_FacingRightAndNotMovingRightAndMovingDown_SetsDirectionToDown( void );
void Npc_Tic_FacingRightAndNotMovingRightAndNotMovingDownAndMovingLeft_SetsDirectionToLeft( void );
void Npc_Tic_FacingRightAndNotMovingRightAndNotMovingDownAndNotMovingLeft_SetsDirectionToUp( void );
void Npc_Tic_FacingDownAndNotMovingDownAndMovingLeft_SetsDirectionToLeft( void );
void Npc_Tic_FacingDownAndNotMovingDownAndNotMovingLeftAndMovingUp_SetsDirectionToUp( void );
void Npc_Tic_FacingDownAndNotMovingDownAndNotMovingLeftAndNotMovingUp_SetsDirectionToRight( void );

// test_player.c
void Player_ResetChaining_Always_ResetsParameters( void );
void Player_UpdateLevel_NoExperience_SetsCorrectLevel( void );
void Player_UpdateLevel_MaxExperience_SetsCorrectLevel( void );
void Player_UpdateLevel_MidExperienceAlmostNextLevel_SetsCorrectLevel( void );
void Player_UpdateLevel_MidExperienceExactlyNextLevel_SetsCorrectLevel( void );

// test_sprite.c
void ActiveSprite_Init_Always_InitializesParameters( void );
void ActiveSprite_SetDirection_DirectionHasNotChanged_DoesNotResetFrame( void );
void ActiveSprite_SetDirection_DirectionHasChanged_ResetsFrameAndChangesDirection( void );
void ActiveSprite_Tic_FrameSecondsHasNotExceededTotal_FrameAndFrameSecondsDoNotChange( void );
void ActiveSprite_Tic_FrameSecondsHasExceededTotal_ResetsFrameSecondsAndIncrementsFrame( void );
void ActiveSprite_Tic_LastFrameAndFrameSecondsHasExceededTotal_SetsFrameToZero( void );

// test_tile_map.c
void TileMap_Init_Always_InitializesParameters( void );
void TileMap_Tic_Always_TicsNpcs( void );
void TileMap_Tic_Always_TicsActiveSprites( void );
void TileMap_Tic_Always_TicsPlayerSprites( void );
void TileMap_CenterEntityOnTile_Always_UpdatesEntityTileIndex( void );
void TileMap_CenterEntityOnTile_Always_CentersEntityOnCorrectTile( void );
void TileMap_GetTileIndexAtPosition_Always_ReturnsCorrectTileIndex( void );
void TileMap_GetPositionOfTileIndex_Always_ReturnsCorrectTileIndexPosition( void );
void TileMap_TileIndexIsEdgeTile_TileIndexIsNotEdgeTile_ReturnsFalse( void );
void TileMap_TileIndexIsEdgeTile_TileMapWraps_ReturnsFalse( void );
void TileMap_TileIndexIsEdgeTile_TileIndexIsLeftEdgeTile_ReturnsTrue( void );
void TileMap_TileIndexIsEdgeTile_TileIndexIsTopEdgeTile_ReturnsTrue( void );
void TileMap_TileIndexIsEdgeTile_TileIndexIsRightEdgeTile_ReturnsTrue( void );
void TileMap_TileIndexIsEdgeTile_TileIndexIsBottomEdgeTile_ReturnsTrue( void );
void TileMap_GetTileVelocity_TileHasNormalSpeedFactor_ReturnsNormalWalkSpeed( void );
void TileMap_GetTileVelocity_TileHasSlowSpeedFactor_ReturnsSlowWalkSpeed( void );
void TileMap_GetTileVelocity_TileHasVerySlowSpeedFactor_ReturnsVerySlowWalkSpeed( void );
void TileMap_GetTileVelocity_TileHasCrawlSpeedFactor_ReturnsCrawlWalkSpeed( void );
void TileMap_GetTileVelocity_PlayerIsOnRamiaWithNonNormalSpeedFactor_ReturnsNormalWalkSpeed( void );
void TileMap_GetTileDiagonalVelocity_NormalWalkSpeed_ReturnsNormalDiagonalSpeed( void );
void TileMap_GetTileDiagonalVelocity_SlowWalkSpeed_ReturnsNormalDiagonalSpeed( void );
void TileMap_GetTileDiagonalVelocity_VerySlowWalkSpeed_ReturnsNormalDiagonalSpeed( void );
void TileMap_GetTileDiagonalVelocity_CrawlWalkSpeed_ReturnsNormalDiagonalSpeed( void );
void TileMap_GetTileDiagonalVelocity_UnknownWalkSpeed_ReturnsCalculatedDiagonalSpeed( void );
void TileMap_ClampViewportToEntity_EdgeOfMapAndTileMapWraps_ClampsToFocalEntity( void );
void TileMap_ClampViewportToEntity_MapIsThinnerThanViewport_ClampsHorizontally( void );
void TileMap_ClampViewportToEntity_MapIsShorterThanViewport_ClampsVertically( void );
void TileMap_ClampViewportToEntity_CloseToLeftEdge_ClampsToScreen( void );
void TileMap_ClampViewportToEntity_CloseToTopEdge_ClampsToScreen( void );
void TileMap_ClampViewportToEntity_CloseToRightEdge_ClampsToScreen( void );
void TileMap_ClampViewportToEntity_CloseToBottomEdge_ClampsToScreen( void );
void TileMap_ClampViewportToEntity_NotCloseToEdge_ClampsToEntity( void );

// test_validate_save.c
void Validate_PlayerCount_TooFewPlayers_ReturnsFalse( void );
void Validate_PlayerCount_TooManyPlayers_ReturnsFalse( void );
void Validate_PlayerCount_EnoughPlayers_ReturnsTrue( void );
void Validate_PlayerName_TooShort_ReturnsFalse( void );
void Validate_PlayerName_TooLong_ReturnsFalse( void );
void Validate_PlayerName_GoodLength_ReturnsTrue( void );
void Validate_PlayerClass_TooLow_ReturnsFalse( void );
void Validate_PlayerClass_TooHigh_ReturnsFalse( void );
void Validate_PlayerClass_GoodClass_ReturnsTrue( void );
void Validate_PlayerGender_TooLow_ReturnsFalse( void );
void Validate_PlayerGender_TooHigh_ReturnsFalse( void );
void Validate_PlayerGender_GoodGender_ReturnsTrue( void );
void Validate_SingleHero_NoHeroes_ReturnsFalse( void );
void Validate_SingleHero_MultipleHeroes_ReturnsFalse( void );
void Validate_SingleHero_OneHero_ReturnsTrue( void );

#endif // TEST_MAIN_H
